### ISSUE TITLE
Clicking Authorize under bot application on Glimesh

### ISSUE THREAD

**Issue by TS-Steve** [aMytho/GlimBoi#70]
When clicking Authorize while viewing my bot application at the very bottom, it returns an error that this site cannot be reached. If I click Authorize I should be presented with a message from Glimboi that my token has been saved or Glimboi has been authorized for 6 hours, etc. If someone else new to this clicks Authorize and is presented with that they may think the program is broken and uninstall it.

**Comment by aMytho** [comment]
After 1.6 the bot doesn't host an authorization server anymore. Instead it uses client credentials (basic post request with id and secret). I only requested that the URL be used in case I have to go back to the old auth method. That is unlikely, but it would prevent users from having to go back and setting the URL later. Any URL would work since it is unused.

As our overlay evolves I may have the bot host a webserver. I could add a endpoint for it but I want to stay with wss to use less resources if possible.

**Comment by TS-Steve** [comment]
Gotcha thanks for the info.
