### ISSUE TITLE
Disconnects randomly from chat

### ISSUE THREAD

**Issue by TS-Steve** [aMytho/GlimBoi#93]
The bot randomly disconnects from chat then I have to reconnect it. I'm not sure why it disconnects but it always does it randomly while streaming or while I'm just testing the chat commands and other features.

**Comment by MythoAway** [comment]
Known bug. v1.9.7 (should be released tonight) should help to lower that and enable automatic chat reconnection when the disconnect happens.

I'm still not certain on what causes the disconnects, so until I can fully prevent them the reconnection should help. I found some potential causes and fixed them, but since the websocket code is 1000 and no reason is given its not easy to fix.

**Comment by TS-Steve** [comment]
Gotcha, thanks for letting me know though.
